### ISSUE TITLE
need way to work with secure websockets (wss)

### ISSUE THREAD

**Issue by catmando** [fkchang/opal-hot-reloader#10]
write now work around is to enable in the browser but this capability is deprecated!

**Comment by fkchang** [comment]
What's the setup you are doing to have secure websockets? I'll want to setup the same or similar to test against

**Comment by fkchang** [comment]
Oh see in the opal gitter you are using cloud9

**Comment by catmando** [comment]
I have it all working, and will do a PR shortly with this and another fix
